version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "github.com/wal-g/tracelog"
      - dependency-name: "go.opentelemetry.io/otel"
      - dependency-name: "go.opentelemetry.io/otel/*"
      - dependency-name: "github.com/Azure/azure-sdk-for-go/*"
      - dependency-name: "cloud.google.com/go"
      - dependency-name: "cloud.google.com/go/*"
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/otel/*"
      azure-sdk:
        patterns:
          - "github.com/Azure/azure-sdk-for-go/*"
      google-cloud-go:
        patterns:
          - "cloud.google.com/go"
          - "cloud.google.com/go/*"
  - package-ecosystem: "gomod"
    directory: "/cmd/pg/exporter"
    schedule:
      interval: "weekly"
